name: metabodashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - astroid=2.3.2
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - colorama=0.4.1
  - cycler=0.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - importlib_metadata=1.5.0
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - jedi=0.16.0
  - joblib=0.13.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.1.0
  - jupyter_core=4.6.1
  - kiwisolver=1.1.0
  - lazy-object-proxy=1.4.3
  - libpng=1.6.37
  - libsodium=1.0.16
  - llvmlite=0.31.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - msys2-conda-epoch=20160418
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - notebook=6.0.3
  - numba=0.48.0
  - numpy=1.17.3
  - numpy-base=1.17.3
  - openssl=1.1.1g
  - pandas=0.25.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.1
  - patsy=0.5.1
  - pickleshare=0.7.5
  - pip=19.3.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - pygments=2.5.2
  - pylint=2.4.3
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.15.7
  - python=3.7.5
  - python-dateutil=2.8.0
  - pytz=2019.3
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.6.0
  - scikit-learn=0.23.1
  - scipy=1.3.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.6.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.30.1
  - statsmodels=0.10.1
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tornado=6.0.3
  - traitlets=4.3.3
  - umap-learn=0.3.10
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - xlrd=1.2.0
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - pip:
    - click==7.0
    - cvxopt==1.2.5
    - dash==1.13.4
    - dash-bio==0.4.8
    - dash-core-components==1.10.1
    - dash-html-components==1.0.3
    - dash-renderer==1.5.1
    - dash-table==4.8.1
    - fastcluster==1.1.26
    - flask==1.1.1
    - flask-compress==1.4.0
    - future==0.18.2
    - intel-openmp==2019.0
    - itsdangerous==1.1.0
    - jinja2==2.10.3
    - mkl==2019.0
    - plotly==4.2.1
    - retrying==1.3.3
    - werkzeug==0.16.0

